server: 
	scp -r server marcus@80.210.72.189:/home/marcus/games/christmasGiftGame
bin: 
	scp -r server/bin marcus@80.210.72.189:/home/marcus/games/christmasGiftGame/server/bin
js: 
	scp -r server/server.js marcus@80.210.72.189:/home/marcus/games/christmasGiftGame/server/
